spring:
  application:
    name: migrationdemo

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,info"

resilience4j:
  retry:
    instances:
      findAllNames:
        max-attempts: 3
        wait-duration: 500ms