spring:
  application:
    name: migrationdemo
    
  mvc:
    apiversion:
      supported: v1,v2
      default: v1
      enabled: true
      use:
        header: X-API-Version

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,info"