spring:
  application:
    name: migrationdemo-integration-test
  datasource:
    url: jdbc:h2:mem:integrationtestdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: false

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,info"

resilience4j:
  retry:
    instances:
      findAllNames:
        max-attempts: 10
        wait-duration: 10ms

logging:
  level:
    com.felipestanzani.migrationdemo: DEBUG
    org.springframework: WARN
    org.hibernate: WARN
